sudo: required 
dist: trusty

services:
    - docker

install:
    - make mysql
    - sleep 30
    - make initmysql
    - docker-compose run -d models  

script:
    - make travis

after_script:
    - docker-compose stop 
    - make stopmysql
