sudo: required 
dist: yakkety

services:
    - docker

install:
    - make mysql
    - sleep 30
    - make initmysql
    - docker-compose up -d 

script:
    - make test

after_script:
    - docker-compose stop
    - make stopmysql
