models:
  build: ./models
  external_links:
    -  mysql
  volumes:
    - "$PWD/models:/app"
  ports:
    - "8002:80"
    - "8082:8080"
  command: bash -c "python /app/manage.py migrate && python /app/manage.py loaddata /app/fixtures.json && mod_wsgi-express start-server --reload-on-changes /app/models/wsgi.py --url-alias /static /app/collected_static"

exp:
  build: ./exp
  links:
    - models
  volumes:
    - "$PWD/exp:/app"
  ports:
    - "8001:80"
    - "8081:8080"
  command: bash -c "python /app/manage.py migrate && mod_wsgi-express start-server --reload-on-changes /app/exp/wsgi.py --url-alias /static /app/collected_static"

web:
  build: ./web
  links:
    - exp
  volumes:
    - "$PWD/web:/app"
  ports:
    - "8000:80"
    - "8080:8080"
  command: bash -c "python /app/manage.py migrate && mod_wsgi-express start-server --reload-on-changes /app/web/wsgi.py --url-alias /static /app/collected_static"

