models:
  build: ./models
  links:
    -  db:db
  volumes:
    - "$PWD/models/src:/app"
  ports:
    - "8000:8000"
    - "8080:8080"
  command: bash -c "mod_wsgi-express start-server --reload-on-changes /app/models/wsgi.py --port 8000"

db:
  image: mysql:5.7.14
  environment:
    MYSQL_ROOT_PASSWORD: '$$3cureUS'
  volumes:
    - db/:/var/lib/mysql

